config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'sessions#new'

  resources :users, only: [:new, :create, :index, :show]

  resource :session, only: [:new, :create, :destroy]

  resources :books do
    resources :reviews
  end

end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :user
    belongs_to :category
    has_many :reviews

    has_attached_file :book_img, styles: { :book_index => "250x375>", :book_show => "350x500>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :book_img, content_type: /\Aimage\/.*\z/
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    before_action :find_book, only: [:show, :edit, :update, :destroy]

    
    #index view shows books in a descending order by creation
    #also allows to show books via the drop down genre selector
    def index
        if  params[:category].blank?
            @books = Book.all.order("created_at DESC")
        else
            @category_id = Category.find_by(name: params[:category]).id
            @books = Book.where(:category_id => @category_id).order("created_at DESC")
        end
    end

    #show view religates unrated books to show at 0 stars by default
    #for the avg rating otherwise the ratings will be averaged
	def show
		if @book.reviews.blank?
			@average_review = 0
		else
			@average_review = @book.reviews.average(:rating).round(2)
		end
	end

    #new book creation and relegated to categories
    def new 
        @book = current_user.books.build
        @categories = Category.all.map{ |f| [f.name, f.id] }
    end

    #create books via private book parameters described below
    #if a book is successfully saved then the all books page
    #will render otherwise create screen will show again
    def create 
        @book = current_user.books.build(book_params)
        @book.category_id = params[:category_id]

        if @book.save
            redirect_to books_path
        else 
            render 'new'
        end
    end

    #allows edit 
    def edit
        @categories = Category.all.map{ |c| [c.name, c.id] }
    end

    #allows books to be edited and updated and if successful
    #it will rerender the single book view otherwise the edit
    #view will be displayed
    def update
        @book.category_id = params[:category_id]
        if @book.update(book_params)
            redirect_to book_path(@book)
        else
            render 'edit'
        end
    end

    #delete a book and render all books page
    def destroy
        @book.destroy
        redirect_to books_path
    end

    private
    #defines parameters for a book
    def book_params
        params.require(:book).permit(:title, :description, :author, :category_id, :book_img)
    end
    #searches for individual book via id number
    def find_book
        @book = Book.find(params[:id])
    end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%-# multipart allows for paperclip to work -%>
<%-# simple form gem allows for creation of forms using the following format -%>
<%= simple_form_for @book, :html => { :multipart => true } do |f| %>
    <%= select_tag(:category_id, options_for_select(@categories), :prompt => "Select a Genre")%>
    <%= f.file_field :book_img %>
    <%= f.input :title, label: "Book Title" %>
    <%= f.input :description, label: "Description" %>
    <%= f.input :author, label: "Author" %>
    <%= f.button :submit %>
<% end %>

app/views/books/edit.html.erb
<h1> Edit Book</h1>
<%-# multipart allows for paperclip to work -%>
<%-# simple form gem allows for creation of forms using the following format -%>
<%= simple_form_for @book, :html => { :multipart => true } do |f| %>
    <%= f.select :category_id, @categories %>
    <%= f.file_field :book_img %>
    <%= f.input :title, label: "Book Title" %>
    <%= f.input :description, label: "Description" %>
    <%= f.input :author, label: "Author" %>
    <%= f.button :submit %>
<% end %>

app/views/books/index.html.erb
<h1 class="current-category"> <%= params[:category] %> </h1>
<%-# allows display of books based on genre -%>
<%-# if there are no books it will state there arent any under that category -%>

<% if @books.count == 0 %>
    <h2>There are no <%= params[:category] %> books currently.</h2>
<% else %>
    <div class="row container">
        <% @books.each do |book| %>
    
            <div class="col-md-4">
                <a href="/books/<%= book.id %>">
                    <%= image_tag book.book_img.url(:book_index), class:book %>
                </a>
            </div>
<% end %>   
    </div>

<% end %>

app/views/books/new.html.erb
<h1>New Book Template</h1>
<%-# renders form partial for books -%>

<%= render 'form' %>

app/views/books/show.html.erb
<div class="row">
    <div class="col-md-4">
        <%= image_tag @book.book_img.url(:book_show), class: "showBook" %>
    </div>
    <%-# iterates through book values to display title author etc -%>
    <div class="col-md-8">
        <h1> <%= @book.title %> </h1>
        <hr/>
        <h3> Author: <%= @book.author %> </h3>
        <h3> Genre: <%= @book.category.name %></h3>
        <h4> Average Rating </h4>
        <div class="average-review-rating" data-score=<%= @average_review%>></div>
        <span><%= @book.reviews.count %> total reviews</span>
        <h1> </h1>
        <p> <%= @book.description%> </p>
    </div>

</div>

    <div class="row">
    <%-# limits reviews to logged in users while unregistered/not logged in persons can only view it -%>
        <div class="col-md-8 pull-right">
            <%= render @book.reviews %>
            <div>
                <% if current_user %>
                    <%= link_to "Add Review", new_book_review_path(@book) %>
                <% end %>
            </div>

        </div>
    </div>

    <%-# raty command script that allows functionality for the star ratings as an average to show -%>
<script>
    $('.review-rating').raty({
        readOnly: true,
        score: function() {
            return $(this).attr('data-score');
        },
        path: '/assets/'
    });
</script>

<script>
    $('.average-review-rating').raty({
        readOnly: true,
        path: '/assets/',
        score: function() {
            return $(this).attr('data-score')
        }
    });
</script>