config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'sessions#new'

  resources :users, only: [:new, :create, :index, :show]

  resource :session, only: [:new, :create, :destroy]

  resources :books do
    resources :reviews
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    #before any method is carried out a book and review will be searched for
    #based on private methods found below
    before_action :find_book
    before_action :find_review, only: [:edit, :update, :destroy] 

    #sets a new review
    def new
        @review = Review.new
    end

    #creation of new review based on userid if successful the individual book
    #that has been rated will show otherwise a review view will be shown
    def create
        @review = Review.new(review_params)
        @review.book_id = @book.id
        @review.user_id = current_user.id

        if @review.save
            redirect_to book_path(@book)
        else
            render 'new'
        end
    end

    def edit
    end

    #change a review and redirects to the book that the review was changed for
    #if unsuccessful then rerenders the edit review view
    def update
        if @review.update(review_params)
            redirect_to book_path(@book)
        else
            render 'edit'
        end
    end

    #allows for a review to be deleted
    def destroy
        @review.destroy
        redirect_to book_path(@book)
    end
    
    private

    #defines parameters for a review
        def review_params
            params.require(:review).permit(:rating, :comment)
        end
    #finds book via id number
        def find_book
            @book = Book.find(params[:book_id])
        end
    #finds review via id number
        def find_review
            @review = Review.find(params[:id])
        end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%-# form partial for rating with raty gem -%>
<%= simple_form_for([@book, @book.reviews.build]) do |f| %>
    <div id="rating-form">
        <label>Rating</label>
    </div>
    <%= f.input :comment %>
    <%= f.button :submit %>
<% end %>

<%-# raty jquery to show star based ratings -%>
<script>
    $('#rating-form').raty({
        path: '/assets',
        scoreName: 'review[rating]'
    });
</script>

app/views/reviews/_review.html.erb
<div class="review-rating" data-score="<%= review.rating %>"></div>
<p><%= review.comment %><p>
<%-# allows the user that commented to edit or delete -%>
<% if current_user %>

    <% if review.user_id == current_user.id %>
        <%= link_to "Edit", edit_book_review_path(review.book, review) %>
        <%= link_to "Delete", book_review_path(review.book, review), method: :delete %>
    <% end %>

<% end %>

app/views/reviews/edit.html.erb
<h1> Edit Review </h1>
<%-# lets user that commented edit their review -%>
<div>
    <%= simple_form_for([@book, @review]) do |f| %>
        <div id="rating-form">
            <label>Rating</label>
        </div>
        <%= f.input :comment %>
        <%= f.button :submit %>
    <% end %>
</div>
<%-# raty jquery to display star rating -%>
<script>
$('#rating-form').raty({
    path: '/assets/',
    scoreName: 'review[rating]'
});
</script>

app/views/reviews/new.html.erb
<h1>New Review</h1>
<%-# renders form partial for reviews -%>
<%= render 'form' %>