config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'sessions#new'

  resources :users, only: [:new, :create, :index, :show]

  resource :session, only: [:new, :create, :destroy]

  resources :books do
    resources :reviews
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LibraryApp</title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Libre+Barcode+39+Text" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class='hero'>
    <%-# bootstrapped various components which show based on user logged in or not -%>
    <nav class="navbar navbar-default">

      <div class="container">

        <div class="navbar-header">
          <%= link_to "Readit", books_path, class: "navbar-brand"%>
        </div>

          <ul class="nav navbar-nav">
              <% if current_user %>
                <li><%= link_to "Sign Out", session_path, method: :delete %></li>
              <% else %>
                <li><%= link_to "Log In", new_session_path %></li>
                <li><%= link_to "Sign Up", new_user_path %></li>
              <% end %>
          </ul>

          <ul class="nav navbar-nav navbar-right">

            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"> Genres <span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
                  <% Category.all.each do |category| %>
                    <li class="<%= 'active' if params[:category] == category.name %>">
                    <%= link_to category.name, books_path(category: category.name), class: "link" %></li>
                  <% end %>
                </ul>
            </li>
          </ul>
          
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "All Books", books_path %></li>
          </ul>

          <ul class="nav navbar-nav navbar-right">
          <% if current_user %>
            <li><%= link_to "Add Book", new_book_path %></li>
          <% end %>
          </ul>
      </div>


      <% if flash[:notice].present? %>
        <div class="notice">
        <%= flash[:notice] %>
        </div>
      <% end %>

      <% if flash[:error].present? %>
        <div class="errors">
        <b>Errors:</b>
        <%= flash[:error] %>
        </div>
      <% end %>

    </div>
    
    <%= yield %>
  </body>
</html>